### ISSUE TITLE
Feature Request: run script by section(s)

### ISSUE THREAD

**Issue by mkillewald** [diego-treitos/linux-smart-enumeration#1]
Great work so far! I think It would be cool if after running a default scan, you could expand or re-run a particular section or sections with a deeper verbose level. For example,

$ ./lse.sh --section 'sudo,security,file system' -l 2

**Comment by diego-treitos** [comment]
Thank you for your suggestion. That is indeed a great idea!

I will have to look into it because some tests use the results of other tests so I have to find a way to handle the dependencies.

**Comment by diego-treitos** [comment]
This issue should be solved with the release of [version 1.0](https://github.com/diego-treitos/linux-smart-enumeration/commit/6191256773723abcbd6b83ea89846e9f844bdc48)

This version allows the inclusion of a parameter `-s` that allows the selection of _sections_ or specific _tests_
