### ISSUE TITLE
\e[ characters not rendering in macOS Terminal.app

### ISSUE THREAD

**Issue by jasikpark** [diego-treitos/linux-smart-enumeration#12]
I suppose this tool is explicitly built for Linux, not Unix/macOS, but for some reason there's a UI element that renders as text rather than what it's supposed to render to.

<img width="1389" alt="Screenshot 2019-07-12 11 14 38" src="https://user-images.githubusercontent.com/10626596/61142923-8a121000-a496-11e9-8da9-b97797fdd525.png">

All of the \e[### characters just show up as the raw text.

I'm using macOS 10.14.5 on a 2016 Macbook Pro with v 2.9.5 of Terminal.app

**Comment by diego-treitos** [comment]
Hello @jasikpark , it is true that the tool is designed to work on Linux systems (hence the name...). However I took a quick look and I think I can improve compatibility a bit regarding ANSI codes.
I've just created a branch for this. Could you test this version and let me know how it goes? (https://github.com/diego-treitos/linux-smart-enumeration/blob/ansifix01/lse.sh)

**Comment by jasikpark** [comment]
perfect!

<img width="1389" alt="Screenshot 2019-07-12 17 02 48" src="https://user-images.githubusercontent.com/10626596/61160985-6dda9700-a4c7-11e9-814a-6091f6915d89.png">

**Comment by jasikpark** [comment]
apparently I use Linux 18.6.0 😅

**Comment by jasikpark** [comment]
<img width="752" alt="Screenshot 2019-07-12 17 14 10" src="https://user-images.githubusercontent.com/10626596/61161231-957e2f00-a4c8-11e9-9f41-c8bcb5be3de1.png">

**Comment by diego-treitos** [comment]
I am glad it works for you now. I will look into merging this branch, but I will do some tests before.

> apparently I use Linux 18.6.0 sweat_smile

Hehe, apparently the tool is sometimes too _smart_  :)

**Comment by diego-treitos** [comment]
I am intrigued... seeing that it successfully finished in macOS. This might mean that many tests could be useful for other Unix flavors too, which is cool!

**Comment by jasikpark** [comment]
Yep! It skipped many of the non-applicable tests, but that's what I would expect!

**Comment by diego-treitos** [comment]
That is fantastic! Thank you for the information!

**Comment by diego-treitos** [comment]
Fix merged to `master` in [1.6](https://github.com/diego-treitos/linux-smart-enumeration/releases/tag/1.6)
