### ISSUE TITLE
Issues with 'SSH files in home directories'

### ISSUE THREAD

**Issue by exploide** [diego-treitos/linux-smart-enumeration#19]
I encountered issues with the *SSH files in home directories* test. There are several ways to fix it, but I'm not sure about the best solution. So I open an issue instead of a PR and you can decide what's best.

First, I noticed the test returns duplicate entries, listing the same file several times. This is annoying and unnecessary so I wanted to fix that.

The reason this happens is because the test iterates over `cut -d: -f6 /etc/passwd`. There are system accounts having `/` as a home directory. So the test repeatedly scans the same directories (actually the whole file system). Furthermore, there are other accounts having something like `/sbin` as home, and so on.

This produces not only duplicate results, it is also unnecessarily slow because it scans the same directories multiple times.

A possible way to reduce duplicates and speed this up is to `sort -u` the `cut -d: -f6 /etc/passwd` first. But since some "home" can be a parent directory of another "home" (think of `/` again), this would still produce duplicates. Duplicates could be filtered by `sort -u` the end result again.

However, this solution still involves unnecessarily scanning the same directories. Maybe we want to exclude `/` if it is in the list. On the other hand, it is perfectly possible that some SSH key lies somewhere on the file system, not within a home. So this check can be handy. Alternatively the test could be changed from "in home directories" to "on the file system" and scan `/` and just `/`.

**Comment by exploide** [comment]
And another thing: The test currently only finds DSA and RSA keys. For completeness, I would also search for `id_ecdsa` and `id_ed25519`.

**Comment by diego-treitos** [comment]
@exploide thanks a lot for reporting the problem.

I think I fixed both of your requests in the new version `1.11`

1. I removed duplicated home directories and removed others like `/`,`/dev/`,`/proc`,`/bin`,`/run/.*` and `/var/run/.*`

2. I added the other key formats to the search.

Please feel free to test and report back in case it is not working as expected or it can be further improved.
