### ISSUE TITLE
Noticed you were working on a LinEnum fork.

### ISSUE THREAD

**Issue by NullArray** [diego-treitos/linux-smart-enumeration#2]
The ticket you opened [here](https://github.com/rebootuser/LinEnum/issues/31) showed up in my notification box. I took a moment to read what you had written there, and had a quick look at your source code. It's looking pretty neat so far.

Now the reason i wanted to open this ticket and get in touch is because i wrote a tool a while ago that automatically downloads and deploys several enumeration,  privilege-escalation and other useful tools for when an initial compromise is made. The focus of my script is to make it as convenient as possible to deploy the best tooling for the job of getting root. My tool is called RootHelper and if you're interested you can find it in it's repo [here](https://github.com/NullArray/RootHelper).

Would i be correct in thinking that your project outclasses LinEnum in terms of sophistication and capabilities? Do you have any plans to further expand on the functionality of the tool?

Either way, i was thinking i might drop LinEnum as a downloadable asset from my RootHelper tool and replace it with your modernized and in many ways improved version. If and when i do you will be accredited for your work of course. Thoughts?

**Comment by diego-treitos** [comment]
Hi @NullArray, thank you for your interest in this tool. Please, feel free to include it in your **RootHelper** script. At the end of the day, it is free software :) and I also borrowed from LinEnum.

The LinEnum tool is a great tool, although it works in a different way. I think it was designed to gather and collect information about a linux system.
LSE tries to give importance to the information that is useful for a privesc, but lacks of the "export" functionality that LinEnum has. I coded LSE to be able to see security flaws in a system in a more organized and progressive way so I think it might be better for a privesc scenario.
In any case I will try to include new tests and keep the tool updated. Hopefully some people will add suggestions and collaborate to improve it.

**Comment by diego-treitos** [comment]
I've been taking a look to your script and it is great to have an script to get all the privesc stuff together. I took the liberty to add some changes in your script so hopefully it would be a bit easier to manage it. Feel free to include or discard the PR as you wish. https://github.com/NullArray/RootHelper/pull/6

Thanks again for your consideration and your tool!

**Comment by NullArray** [comment]
Thank you for the kind words, and thank you for your Pull Request, i'll go over the changes as soon as i hit the "comment" button on this post. 

Yeah, RootHelper was made with privilege escalation in mind. The enumeration scripts that are available through it are there to gather information to that end. In that sense, an enumeration script that was built with privilege escalation in mind would be a better fit with the overall purpose of RootHelper. Which is of course why i am interested in replacing LinEnum with your implementation.

Checking out your PR in 3, 2, 1...

**Comment by NullArray** [comment]
Alright. Just merged the PR, while i was at it i added some new functionality including operations to download your tool.

Check out the commit history below if you're interested.

https://github.com/NullArray/RootHelper/commit/a7f03cc8dc31eb120c5861da69899f72109c4cae

**Comment by diego-treitos** [comment]
Thank you @NullArray for adding LSE to your script. I saw that you added a "tip of the day" feature, haha. Nice.

I guess we can close this ticket now.
