### ISSUE TITLE
Other useful oneliners

### ISSUE THREAD

**Issue by nemesis7331** [diego-treitos/linux-smart-enumeration#22]
Hi! 
great work with this project! 
as additional oneliners I would suggest you the followings:
```bash
bash <(wget -q -O - https://raw.githubusercontent.com/diego-treitos/linux-smart-enumeration/master/lse.sh) -l2 -i
bash <(curl -s https://raw.githubusercontent.com/diego-treitos/linux-smart-enumeration/master/lse.sh) -l2 -i
```
keep up the good work!

**Comment by diego-treitos** [comment]
Thank you, I added them to the readme in an Examples section.

Thanks for your kind words and for taking your time to help to improve the tool.
