### ISSUE TITLE
Group process running per user

### ISSUE THREAD

**Issue by Techbrunch** [diego-treitos/linux-smart-enumeration#25]
Hello @diego-treitos ,

First thank you for this tool.

I was wondering if it would be a good addition to list running process per user instead of all running processes. Or maybe users with a shell.

I think this would help identify interesting running processes quicker.

Let me know if you would be interested by something like this and I'll see what I can do.

**Comment by diego-treitos** [comment]
Hello @Techbrunch I like the idea very much. Listing processes belonging to users that have shell is certainly interesting. Thank you for the idea!

I am looking into it.

**Comment by diego-treitos** [comment]
I created a branch with a new test that should include your idea: https://github.com/diego-treitos/linux-smart-enumeration/blob/fix%2325/lse.sh

I added the test `pro020`. You can test it with `./lse.sh -i -l1  -s pro020,usr030`.

Please, let me know if this is what you asked for. If everything is ok I will merge it to `master`

**Comment by Techbrunch** [comment]
Perfect !

```
==================================================================( users )=====
[*] usr030 Other users with shell.......................................... yes!
---
root:x:0:0:root:/root:/bin/bash
tom:x:1000:1000:tom,,,:/home/tom:/bin/bash
mark:x:1001:1001:Mark,,,:/home/mark:/bin/bash
---
==============================================================( processes )=====
[*] pro020 Processes running by non-root users with shell.................. yes!
---


------ tom ------


UID        PID  PPID  C STIME TTY          TIME CMD
tom       1219     1  0 Mar30 ?        00:00:12 /usr/bin/node /var/www/myplace/app.js
tom       1408     1  0 Mar30 ?        00:00:12 /usr/bin/node /var/scheduler/app.js


------ mark ------


UID        PID  PPID  C STIME TTY          TIME CMD
mark     20297     1  0 14:31 ?        00:00:00 /lib/systemd/systemd --user
mark     20302 20297  0 14:31 ?        00:00:00 (sd-pam)
mark     20307 20295  0 14:31 ?        00:00:00 sshd: mark@pts/0
mark     20308 20307  0 14:31 pts/0    00:00:00 -bash
mark     20335 20308  0 14:34 pts/0    00:00:00 /bin/bash ./lse.sh -i -l1 -s pro020,usr030
mark     20356 20335  0 14:34 pts/0    00:00:00 /bin/bash ./lse.sh -i -l1 -s pro020,usr030
mark     20366 20356  0 14:34 pts/0    00:00:00 ps -u mark -f
---

==================================( FINISHED )==================================
```
