### ISSUE TITLE
List non default directories in the root path

### ISSUE THREAD

**Issue by Techbrunch** [diego-treitos/linux-smart-enumeration#26]
Hello,

I think a nice addition would be to list non-default directories in the root path.

I ran into this situation in a CTF where the interesting files were in `/backup`.

**Comment by diego-treitos** [comment]
Hi again @Techbrunch . Thank you for providing another idea.

In this case I am not convinced that looking for non-default directories is that interesting for a privilege escalation. It might be too generic.

However I think that looking for **readable backups** is actually very interesting.

I am considering to add a test that runs something like:

```
find / -path /usr/share -prune -o -readable -regextype egrep -iregex ".*(backup|dump|copy|bkp)[^/]*\.(sql|tgz|tar|tar\.[a-z0-2]{2,5}|zip|gz|xz|bzip2|bz2|lz|7z)" -print 2> /dev/null
```

This should return files that are **readable backups**.

What do you think about this?

**Comment by diego-treitos** [comment]
I added a check to detect readable backups in version 1.20
