### ISSUE TITLE
syntax error near unexpected token `newline' ./lse.sh: line 166: `lse_common_setuid+=('

### ISSUE THREAD

**Issue by KumarShrawan** [diego-treitos/linux-smart-enumeration#30]
Hi ,
I was trying this script on "  Hostname: kioptrix.level2,  Linux: 2.6.9-55.EL ,Distribution: CentOS release 4.5 (Final) " and I got the below error: 
**bash-3.00$** ./lse.sh
./lse.sh: line 166: syntax error near unexpected token `newline'
./lse.sh: line 166: `lse_common_setuid+=('
bash-3.00$ 

![lse_issue 2020-04-25 at 11 29 42 PM](https://user-images.githubusercontent.com/4800504/80311972-b5a98100-87b0-11ea-8c45-776cf7949384.jpeg)

After commenting line number 166 to 169 , the scripts executes but no fruitful result -  see error-log.txt attached . Quick help is really appreciated.  
[error-log.txt](https://github.com/diego-treitos/linux-smart-enumeration/files/4535727/error-log.txt)

**Comment by diego-treitos** [comment]
Yes, this is a known problem. The scripts requires at least bash 4 with support for arrays.

**Comment by diego-treitos** [comment]
Hi again @KumarShrawan, I've been working a bit to convert the script to be POSIX compliant. I've tested it using `posh` and it seems to work fine.
There is a git branch called `posix` with this version. Could you try it?

`https://raw.githubusercontent.com/diego-treitos/linux-smart-enumeration/posix/lse.sh`

**Comment by mechs85** [comment]
Hi @diego-treitos POSIX version works. Thank you

**Comment by diego-treitos** [comment]
Fantastic, thanks for the feedback. I will switch to the posix compliant branch by default.
