### ISSUE TITLE
additional SSH check

### ISSUE THREAD

**Issue by Barneee** [diego-treitos/linux-smart-enumeration#31]
Hi Diego, 
would be cool if you can add the feature that your script checks for unencrypted ssh-keys in memory (ssh-agent) by calling "ssh-add -l" and check if there are entries present or not. 

Greets,
Barneee

**Comment by diego-treitos** [comment]
Hi Barnee, thank you for your suggestion. I added the test as `sof050` which is now included in version `2.2`.

Cheers

**Comment by Barneee** [comment]
My pleasure. Cool thanks for the quick implementation. 
Greets Barneee
