### ISSUE TITLE
Feature: flag to create output file

### ISSUE THREAD

**Issue by engn33r** [diego-treitos/linux-smart-enumeration#34]
I am not sure if others would find this useful, but some users might want to save the output of this script somewhere. I consider this script to have two outputs: The text printed to the terminal and the output of the commands that are run. Using the -l2 shows both of these outputs, but if there was a way to print -l0 or -l1 information to the terminal but store the -l2 output (output of commands) to a file, then the user could have clean output that is fast to analyze and all the information they might need to reference is also available.

But this might take more effort than it is worth, depending on how useful others would find this.

**Comment by diego-treitos** [comment]
The way the script works is that there are more commands that are executed under `-l2` than under `-l1` or `-l0`. This way the script executes faster in the less verbose levels.

If you want all the output you have to execute under `-l2` and you can redirect all that to a file with `./lse.sh -l2 > output.txt`. You can even keep the colors and then open the file with `less -r output.txt` so you see all the information color coded.

Now if you wanted even more than that, you can edit the script and change `lse_DEBUG=false` to `lse_DEBUG=true` currently in line `85`. This is only using for debugging but you might find it useful if you want to save everything.

**Comment by engn33r** [comment]
Thank you for the ideas!

Setting `lse_DEBUG=true` and using `./lse.sh -l2 > output.txt` is very similar to what I was looking for. The only difference with the idea I was thinking of is that it would be nice if this DEBUG output could be saved, but at the same time, the abbreviated output (such as with `-l1`) could be printed to the terminal. This would allow a user to easily identify what areas to examine in more detail and examine `output.txt` for more details if necessary. Using `./lse.sh -l2 | tee output.txt` would only help a little bit, because there is so much output in the terminal that it is hard to navigate. Of course, the easiest solution is to run the script 2 times, once with `./lse.sh -l1` (to get the short output in the terminal) and once with `./lse.sh -l2 > output.txt` (to get the detailed output)!

I don't know if anyone else would be interested in this particular feature, but if there is interest, I can try to implement this, perhaps using a new optional flag. But for now, I can run the script 2 times when I need this feature.
