### ISSUE TITLE
lse_sudo_commands: readonly variable

### ISSUE THREAD

**Issue by exploide** [diego-treitos/linux-smart-enumeration#37]
When running lse on Debian 10 without `-i` option, the following error occurs:

```
[!] sud030 Can we list sudo commands with a password?......................lse.sh: line 402: lse_sudo_commands: readonly variable
 nope
```

While it continues when running under bash, it aborts completely when running with `/bin/sh`.

**Comment by diego-treitos** [comment]
This should be fixed in version 2.5.

Thanks a lot for reporting it.
