### ISSUE TITLE
LSE Color issues

### ISSUE THREAD

**Issue by oabsixr** [diego-treitos/linux-smart-enumeration#38]
Having a similar issue with the color as (https://github.com/diego-treitos/linux-smart-enumeration/issues/32) while running lse without explicitly running with bash on an older device. A screenshot with some details, not sure if it's enough information for you? 

![image](https://user-images.githubusercontent.com/67179369/91378990-3d34f880-e854-11ea-8897-148a16a52b34.png)
![image](https://user-images.githubusercontent.com/67179369/91379024-4f169b80-e854-11ea-9b52-5b89365f289b.png)

The machine i was trying it on was an old Fedora 4 (Linux 2.6.11-1369_FC4)

**Comment by diego-treitos** [comment]
Hello @oabsixr, thank you for reporting the issue. I had to install a Fedora Core 4 to test and this is indeed an odd bug. I already have a fix and will be available in the next release.
