### ISSUE TITLE
SUID not shown in IRKED

### ISSUE THREAD

**Issue by pai-theredhat** [diego-treitos/linux-smart-enumeration#4]
viewuser SUID was not showing in the Irked machine

**Comment by diego-treitos** [comment]
Yes, I know that the current check for "odd" SUID binaries is quite poor. Currently an "odd" SUID binary is only the one that is outside the common binary paths.

I already thought about improving the check, but for that I would require a list of common SUID binaries from the most known linux distributions. 

I would probably have to install the desktop version (probably it has more software and therefore more SUID binaries) of a couple of `ubuntu LTS`, 3 or 4 `debian`, 3 or 4 `CentOS/RedHat`, 3 or 4 `Fedora` and 3 or 4 `Suse` at least.  From there we could improve adding `CoreOS`, `Alpine`, `Arch`, etc

This will be quite time consuming so I will do my best.

**Comment by pai-theredhat** [comment]
Yes..I understand

**Comment by pai-theredhat** [comment]
U may just start with Ubuntu lts .... Check the os and show accordingly ...and then u can build on new oses as and when you get time

**Comment by pai-theredhat** [comment]
Like  if (os = Ubuntu )
Check against a list

**Comment by diego-treitos** [comment]
Actually I found an easy way to find those binaries for several distributions and I could implement your feature much easier than I though. It should work much better now.
