### ISSUE TITLE
[Request] User Friendly Reports

### ISSUE THREAD

**Issue by zero77** [diego-treitos/linux-smart-enumeration#41]
lse finds lots of useful info but, it can some times be a bit hard to analyze when the reports big and there's lots their.

Having an option to create an html report with hyperlinks and cullers as well as minimizing or expanding sections, would make it easier to analyze the output.
Thanks

**Comment by diego-treitos** [comment]
That is not in the scope of this script sorry. Maybe in the future I can consider to create a formatted output though.
