### ISSUE TITLE
Consider dropping white/black colors

### ISSUE THREAD

**Issue by danielwalo** [diego-treitos/linux-smart-enumeration#44]
Hi. :)

I use Kali in with the High Contrast style. When running lse.sh with colors, this causes the test descriptions to be "blank" because white is hard-coded as the foreground color.

![lse](https://user-images.githubusercontent.com/23709297/113336244-65bf2c80-9326-11eb-8823-f706d9371f9b.png)

I fixed the issue by deleting all instances of ${white} in the script. It's useful to have color highlighting.

**Comment by diego-treitos** [comment]
Hi. Sorry for the delay on the response. 

I gave some thought to this and eventually I decided that it might be good to have an alternative color scheme for these cases.

I created a new branch to test a new color scheme that you can activate with the `-C` (capital C) paramenter, just for you ;).

Please give it a try: https://raw.githubusercontent.com/diego-treitos/linux-smart-enumeration/alt_color/lse.sh

Please let me know what you think and, if it is ok, I will incorporate the changes into the master branch.

**Comment by danielwalo** [comment]
Looks great!

**Comment by diego-treitos** [comment]
Thank you @danielwalo . I've released version `3.2` that includes this change.

I am closing this ticket.

Cheers!
