### ISSUE TITLE
Common setuid binary `fusermount3`

### ISSUE THREAD

**Issue by exploide** [diego-treitos/linux-smart-enumeration#57]
I think `/usr/bin/fusermount3` should be added to the list of common setuid binaries. I have that on my Fedora 35 system and I also saw it on a Debian- or Ubuntu-like box.

```console
$ ls -lh $(which fusermount3)
-rwsr-xr-x. 1 root root 36K 16. Sep 17:59 /usr/bin/fusermount3
```

**Comment by diego-treitos** [comment]
Thank you @exploide . I added this binary and another one.
