### ISSUE TITLE
More infor about distro 

### ISSUE THREAD

**Issue by pai-theredhat** [diego-treitos/linux-smart-enumeration#7]
It would be great if you can add more info about the linux version 

eg:- Ubunt 16.014.1 LTS 

This info is missing 

And A line about if it is dirty cowable would be nice

**Comment by diego-treitos** [comment]
Thank you for the suggestion. I already added it.

Regarding the detectiong of the dirty cow vulnerability, I don't think I can implement that yet. I want this script to be as reliable as posible and, although I looked into it, I did not find any reliable way to detect CVEs in a system.  There are many factors like properly detecting the versions, the distribution custom patching, etc.
In any case adding CVE report is something that I have in mind, but first I need to find a reliable source of CVEs where I can search for software versions and then look into edge cases in distributions.
