### ISSUE TITLE
Syntax error line 87

### ISSUE THREAD

**Issue by Langriklol** [diego-treitos/linux-smart-enumeration#9]
Hi there,
as I wanted to test you script, I am unable to launch it.  The error is:
 `lse.sh: 87: lse.sh: Syntax error: "(" unexpected `

as in the following screen.
![image](https://user-images.githubusercontent.com/20239181/56826725-3f9cd200-685d-11e9-8c9b-99d5bb35bbab.png)

Code snippet:
![image](https://user-images.githubusercontent.com/20239181/56827048-fef18880-685d-11e9-9056-3b79c7d9c5a5.png)

I have looked into the code but as I am not as good as others in Bash I saw nothing bad there. Can you please look for a fix in the  `lse.sh` script? Thank you.

**Comment by diego-treitos** [comment]
You probably have `sh` symlinked to `/bin/dash`.

I am afraid that the script is not POSIX compliant, as it uses arrays, so it requires `bash` to run.

Could you try `bash ./lse.sh` or just `chmod 750 lse.sh; ./lse.sh` ?

**Comment by Langriklol** [comment]
@diego-treitos oh yes.. thats it. Thanks alot! :)

**Comment by diego-treitos** [comment]
You are welcome :). I hope the tool is useful for you.
